### ISSUE TITLE
Compiling ramp on Windows

### ISSUE THREAD

**Issue by alfonso73** [siteswapjuggler/max-objects#1]
hi! 
great stuff!
i have this errors in ramp on VS2013
    1   ramp    IntelliSense: expression must have a constant value 321 17
    2   ramp    IntelliSense: expression must have a constant value 467 21
    3   ramp    IntelliSense: expression must have a constant value 490 29
    4   ramp    IntelliSense: expression must have a constant value 553 21

related to 

t_atom temp[x->r_len];

smoov does comile fine

notice that i got to add

include# <stdint.h> on both sources
and
# define M_PI 3.14159265359

to ramp source

any idea ho to solve the ramp issue?

thanks and all the best

**Comment by siteswapjuggler** [comment]
I didn’t try to compile on windows I’ll check this out as soon as possible and take good notes at your feedbacks.

Sincerely

Sylvain

De : Alfonso Santimone [mailto:notifications@github.com] 
Envoyé : lundi 28 décembre 2015 17:43
À : siteswapjuggler/max-objects
Objet : [max-objects] Compiling ramp on Windows (#1)

hi! 
great stuff!
i have this errors in ramp on VS2013
1 ramp IntelliSense: expression must have a constant value 321 17
2 ramp IntelliSense: expression must have a constant value 467 21
3 ramp IntelliSense: expression must have a constant value 490 29
4 ramp IntelliSense: expression must have a constant value 553 21

related to 

t_atom temp[x->r_len];

smoov does comile fine

notice that i got to add

include# on both sources
and
#define M_PI 314159265359
to ramp source

any idea ho to solve the ramp issue?

thanks and all the best

**Comment by siteswapjuggler** [comment]
Problem solved with a dynamic memory allocation.
Windows version are now compiled in x86 and x64.

**Comment by siteswapjuggler** [comment]
Hello I updated both object (smoov & ramps) and exported them into x86 an x64 windows external.

I let you look for the updates on github : https://github.com/siteswapjuggler/max-objects/

HNY 2016

Sylvain

De : Alfonso Santimone [mailto:notifications@github.com] 
Envoyé : lundi 28 décembre 2015 17:43
À : siteswapjuggler/max-objects
Objet : [max-objects] Compiling ramp on Windows (#1)

hi! 
great stuff!
i have this errors in ramp on VS2013
1 ramp IntelliSense: expression must have a constant value 321 17
2 ramp IntelliSense: expression must have a constant value 467 21
3 ramp IntelliSense: expression must have a constant value 490 29
4 ramp IntelliSense: expression must have a constant value 553 21

related to 

t_atom temp[x->r_len];

smoov does comile fine

notice that i got to add

include# on both sources
and
#define M_PI 314159265359
to ramp source

any idea ho to solve the ramp issue?

thanks and all the best

**Comment by alfonso73** [comment]
many thanks Sylvain!
HAPPY 2016!

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone
